GET http://localhost:8000/user-controller/getUsers

###

POST http://localhost:8000/user-controller/register
Content-Type: application/json
Authorization: Bearer .eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAZXhhbXBsZS5jb20iLCJpYXQiOjE2ODUxMjgzMjAsImV4cCI6MTY4NTIxNDcyMH0.GfzcRv7hWz7p3LFJ9LUGBqJK30QBJB7gkoNDyuKE8C4

{
        "email": "user10@example.com",
        "password": "123456",
        "created_at": "2023-05-16T00:00:00.000Z",
        "updated_at": "2023-05-20T00:00:00.000Z",
        "first_name": "Lidija",
        "last_name": "Stojanovic",
        "tasks" : [{
                "taskDescription": "Buy new dress",
                "created_at": "2023-05-23",
                "updated_at": "2023-05-23",
                "done": 0
}]
}

###

POST http://localhost:8000/auth/login
Content-Type: application/json 

{
        "email": "user1@example.com",
        "password": "123456"
}

###

GET http://localhost:8000/user-controller/numberOfUsers 

###

GET http://localhost:8000/user-controller/numberOfTasks
Content-Type: application/json

###

GET http://localhost:8000/task/get-tasks

###

GET http://localhost:8000/task/userTasks
Content-Type: application/json 

###

POST http://localhost:8000/task/add-task
Content-Type: application/json

{
        "taskDescription": "Go fishing",
        "created_at": "2023-05-21",
        "updated_at": "2023-05-23",
        "done": false
        
} 


